<a href="https://colab.research.google.com/github/Vkgo2309/Assignment-1/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
np.__version__
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
A= np.zeros(10)

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
np.size(A)

10

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [5]:
np.info(A)

class:  ndarray
shape:  (10,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x1926580
byteorder:  little
byteswap:  False
type: float64


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [6]:
A[4]=1
print(A)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [7]:
B= np.arange(10,50)
print(B)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [8]:
B[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [9]:
mat = np.arange(0, 9).reshape((3, 3))
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [10]:
a=[1,2,0,0,4,0]
np.nonzero(a)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [11]:
mat1=np.eye(3,3)
print(mat1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [12]:
 np.random.random((3,3,3))

array([[[0.75356602, 0.95196589, 0.15489725],
        [0.32765519, 0.89698826, 0.8670856 ],
        [0.10408469, 0.52845955, 0.53940902]],

       [[0.3183293 , 0.34952554, 0.68631953],
        [0.22645386, 0.76176447, 0.44375199],
        [0.42793753, 0.7669466 , 0.63823997]],

       [[0.46853875, 0.24682615, 0.01195924],
        [0.44915997, 0.20178578, 0.53038864],
        [0.21217319, 0.35115183, 0.64848198]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [13]:
L=np.random.random((10,10))
Lmin, Lmax = L.min(), L.max()
print(L)
print(Lmin, Lmax)

[[0.10703575 0.81973688 0.01512405 0.7503432  0.49124936 0.46793197
  0.47470606 0.56437957 0.25758297 0.31784875]
 [0.96846626 0.9093782  0.9098916  0.84475931 0.09138902 0.1952776
  0.37910751 0.04426768 0.67724142 0.2472052 ]
 [0.10113034 0.66200109 0.14408242 0.61971504 0.22746645 0.13008842
  0.07677386 0.49332512 0.15519579 0.26006626]
 [0.2151673  0.18977162 0.01504842 0.72898656 0.1382316  0.58328826
  0.36932355 0.06688064 0.0513979  0.80446431]
 [0.1118195  0.1896316  0.08598159 0.47466626 0.80946797 0.38305316
  0.73874062 0.4317975  0.37962984 0.75976808]
 [0.96304064 0.47774135 0.57775599 0.46409193 0.63899965 0.80060577
  0.11968293 0.82316758 0.79495956 0.44590312]
 [0.71514974 0.61702142 0.25509228 0.23281032 0.57703201 0.48781094
  0.7520161  0.59939591 0.59699151 0.0209763 ]
 [0.13149992 0.76630558 0.00575355 0.78600523 0.30328789 0.91455983
  0.75579081 0.63765778 0.45262471 0.87033239]
 [0.35488658 0.3940467  0.0148357  0.24072002 0.94902793 0.23519573
  0.26087949 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [14]:
from numpy.core.fromnumeric import mean
a=np.random.random(30)
print(a)
np.mean(a)

[0.41790812 0.83819272 0.92760081 0.87887155 0.59033441 0.62405641
 0.31055125 0.6613002  0.35775432 0.13155165 0.70040532 0.93190109
 0.49938065 0.87340704 0.88051113 0.13396582 0.05579255 0.53048612
 0.36164569 0.83803969 0.76688604 0.9516183  0.4150988  0.58879539
 0.79456564 0.6221686  0.12638279 0.19152926 0.1066088  0.67931274]


0.55955409653847

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [15]:
x=np.ones((5,5),dtype=int)
x[1:-1,1:-1]=0
print(x)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [16]:
y=np.random.random((2,2))
y=np.pad(y, pad_width=1, mode='constant', constant_values=0)
print(y)

[[0.         0.         0.         0.        ]
 [0.         0.97043355 0.6366703  0.        ]
 [0.         0.84797494 0.38616475 0.        ]
 [0.         0.         0.         0.        ]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [18]:

n=np.diag((1,2,3,4))
print(n)





[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [19]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [20]:
def tiling(n):
    result = np.zeros((n, n),int)
    result[::2, 1::2] = 1
    result[1::2, ::2] = 1
    return result


print(tiling(8))




[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [21]:

x= np.random.random((5,5))
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print(x)

[[0.41368332 0.59777053 0.6195716  0.81920039 0.28904448]
 [0.19192319 0.88652789 0.48301945 0.25934272 0.77777256]
 [0.85179226 0.1958284  0.56458097 0.9615518  0.76285825]
 [0.78236509 0.03058079 0.59359392 0.21235299 0.03475089]
 [0.93053493 0.40182978 0.4060226  0.9680561  0.81315856]]
[[0.40865346 0.60501832 0.62827341 0.8412164  0.27570186]
 [0.17210309 0.91303429 0.48261395 0.24401915 0.79702555]
 [0.87598197 0.17626875 0.56961519 0.9930619  0.78111653]
 [0.80192438 0.         0.60056316 0.19389545 0.00444823]
 [0.95997637 0.39600935 0.40048181 1.         0.8347716 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [22]:
x = np.random.random((5,3))
print(x)
y = np.random.random((3,2))
print(y)
z = np.dot(x, y)
print(z)

[[0.9307668  0.16907304 0.99609592]
 [0.45194946 0.3377643  0.20328808]
 [0.40535175 0.44713702 0.58723702]
 [0.38367797 0.26575021 0.86020401]
 [0.74429802 0.12263777 0.01447245]]
[[0.53949346 0.63232503]
 [0.13070225 0.6415373 ]
 [0.59609729 0.25788734]]
[[1.11801091 0.95389433]
 [0.40914981 0.55489277]
 [0.62717684 0.69461013]
 [0.75449119 0.63493358]
 [0.42619994 0.55304723]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [23]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [24]:
Z=np.arange(0,5)
2 << Z >>2

array([0, 1, 2, 4, 8])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [25]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

In [26]:
np.array(50) // np.array(2)


25

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [27]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [28]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2022-05-28
Today:  2022-05-29
Tomorrow:  2022-05-30


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [29]:
print("July, 2016")
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

July, 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [30]:
A = np.array([1,2,3])
B = np.array([4,5,6])
((A+B)*(-A/2))

array([ -2.5,  -7. , -13.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [31]:
a= np.random.uniform(10,20,25)
print(a)
print(a-a%1) 


[18.91069749 10.18948903 14.41971641 15.53328898 18.64517427 12.617945
 15.72800423 11.57487657 15.30552963 11.43337045 18.60552272 16.30215144
 11.28523348 14.09334998 12.77292723 11.52790755 16.86093953 12.56701772
 16.82073145 13.7803155  10.08959084 18.25435224 10.72332749 10.53624214
 13.75088303]
[18. 10. 14. 15. 18. 12. 15. 11. 15. 11. 18. 16. 11. 14. 12. 11. 16. 12.
 16. 13. 10. 18. 10. 10. 13.]


In [32]:
b=np.random.uniform(0,2,3)
print(b)
print(np.floor(b)) 


[0.80250012 0.35954021 0.49455957]
[0. 0. 0.]


In [33]:
c=np.random.uniform(6,2,5)
print(c)
print(np.ceil(c)-1) 



[2.81204831 3.51287922 4.85647025 3.20435415 3.83045688]
[2. 3. 4. 3. 3.]


In [34]:
d=np.random.uniform(7,10,9)
print(d)
print (d.astype(int))


[9.44556838 8.55656034 7.26935875 7.98725624 9.8547216  8.26053385
 8.40845201 7.76097417 7.54649217]
[9 8 7 7 9 8 8 7 7]


In [35]:
x=np.random.uniform(5,10,18)
print(x)
print (np.trunc(x))

[8.75673217 7.15587598 5.53706059 8.42519985 5.65702003 8.12151739
 5.09377477 5.1708633  7.40604254 9.11950297 6.12782325 6.55722871
 5.47635695 6.9493135  7.30800654 6.03288343 9.91672335 7.51265067]
[8. 7. 5. 8. 5. 8. 5. 5. 7. 9. 6. 6. 5. 6. 7. 6. 9. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [36]:
x = np.zeros((5,5),int)
x += np.arange(5)
print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [37]:
def generate():
   for n in range(10):
       yield n
m = np.fromiter(generate(),dtype=int,count=-1)
print("New array:")
print(m)

New array:
[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [38]:
x = np.linspace(0,1,12,endpoint=True)[1:-1]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [39]:
x=np.random.random(10)
x.sort()
print(x)


[0.0326887  0.06553102 0.26287479 0.28623583 0.36310894 0.46404546
 0.51599745 0.70819429 0.90509341 0.98043644]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [40]:
a=(5,2,9)
b=(2,5,6)
c= np.add.reduce(a+b)
print(c)

29


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [41]:
A = np.random.randint(5,9,4)
print("A:")
print(x)
B = np.random.randint(5,9,4)
print("B:")
print(y)
print("Result")
array_equal = np.allclose(A,B)
print(array_equal)

A:
[0.0326887  0.06553102 0.26287479 0.28623583 0.36310894 0.46404546
 0.51599745 0.70819429 0.90509341 0.98043644]
B:
[[0.53949346 0.63232503]
 [0.13070225 0.6415373 ]
 [0.59609729 0.25788734]]
Result
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [43]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [44]:
a= np.random.random((10,2))
b,c = a[:,0], a[:,1]
x = np.sqrt(b**2+c**2)
y = np.arctan2(b,c)
print(x)
print(y)

[1.1128453  1.11186015 1.00177095 0.90717774 1.00103108 0.41865466
 0.7956555  0.81847336 0.85891537 0.96749657]
[0.57420437 0.80999431 1.30639167 0.69752857 1.16273126 1.16851124
 1.12842467 0.92581555 1.07342611 0.12484359]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [45]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Result:")
print(x)

Original array:
[0.05407477 0.59361552 0.41031129 0.85864316 0.95229914 0.12266657
 0.44208554 0.74510039 0.49995176 0.22526367]
Result:
[0.05407477 0.59361552 0.41031129 0.85864316 0.         0.12266657
 0.44208554 0.74510039 0.49995176 0.22526367]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [46]:
X, Y=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D=np.sqrt(X*X+Y*Y)
sigma, mu=1.0,0.0
G=np.exp(-( (D-mu)**2/(2.0*sigma**2) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [53]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [54]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [55]:
np.set_printoptions
a = np.zeros((5,5),int)
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [56]:
Z = np.arange(50)
v = np.random.uniform(0,50)
index = (np.abs(Z-v)).argmin()
print(Z[index])

30


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [57]:
a = np.zeros(5, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [58]:
Z = np.random.random((100,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

import scipy
import scipy.spatial

Z = np.random.random((100,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.3149597  0.75359737 ... 0.4851388  0.24133647 0.41534193]
 [0.3149597  0.         0.68257232 ... 0.18068228 0.09352687 0.30899694]
 [0.75359737 0.68257232 0.         ... 0.62813108 0.73749649 0.99033778]
 ...
 [0.4851388  0.18068228 0.62813108 ... 0.         0.27362267 0.43105692]
 [0.24133647 0.09352687 0.73749649 ... 0.27362267 0.         0.26046705]
 [0.41534193 0.30899694 0.99033778 ... 0.43105692 0.26046705 0.        ]]
[[0.         0.11726442 0.76693015 ... 0.38251074 0.65559037 0.92234848]
 [0.11726442 0.         0.7958841  ... 0.26739171 0.6030096  0.93848576]
 [0.76693015 0.7958841  0.         ... 0.96324484 0.51358664 0.17698348]
 ...
 [0.38251074 0.26739171 0.96324484 ... 0.         0.62199391 1.07768715]
 [0.65559037 0.6030096  0.51358664 ... 0.62199391 0.         0.54557472]
 [0.92234848 0.93848576 0.17698348 ... 1.07768715 0.54557472 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [59]:
Z = np.arange(10, dtype=np.float32)
print(Z)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [62]:
from io import StringIO


s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)


[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [63]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [64]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
Z = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(Z)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [65]:
n = 10
p = 3
Z = np.zeros((n,n),int)
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [66]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[-0.44944255  0.18675608  0.00760464  0.097512   -0.3384279   0.31638463
  -0.45672807 -0.01583082  0.40938141  0.24279058]
 [-0.30809329 -0.36308911  0.26035372 -0.02139638  0.02869353 -0.29485911
  -0.06634645  0.17632496  0.52921099  0.05920112]
 [-0.1617618  -0.2874222  -0.40004534  0.20868213  0.34364806 -0.37082381
  -0.27828289  0.1707596   0.26870176  0.5065445 ]
 [-0.19617222  0.3997933  -0.07567131  0.06394086  0.0683525   0.1347929
  -0.03952642 -0.50222002 -0.21885107  0.36556149]
 [ 0.16685694 -0.34091321 -0.04585614  0.19146784  0.19235511  0.22701166
   0.24292094 -0.05251092 -0.32196482 -0.25936739]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [67]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[1 9 0]
 [9 5 0]
 [7 9 6]]
[[9 5 0]
 [1 9 0]
 [7 9 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [68]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [69]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4573077880959553


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [70]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
it = np.nditer([a,b,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [71]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [72]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 3. 3. 3. 2. 5. 5. 2. 1. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [73]:
X = [1,2,3,4,5,6]
Y = [1,3,9,3,4,1]
Z = np.bincount(Y,X)
print(Z)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [74]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [75]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[48 39 59 53]
 [61 71 48 57]
 [49 43 39 67]]
[[48 39 59 53]
 [61 71 48 57]
 [49 43 39 67]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [76]:
A = np.random.uniform(0,1,100)
B = np.random.randint(0,10,100)
sums = np.bincount(B, weights=A)
counts = np.bincount(B)
means = sums / counts
print(means)

[0.49602104 0.44725228 0.43888693 0.36596753 0.40585898 0.49466811
 0.57503249 0.6236584  0.66941203 0.39720241]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [77]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([0.89963732, 1.65728143, 0.56440491, 2.26546026, 1.89273704])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [80]:
Z = np.array([1,2,3,4,5])
nz = 3
Y = np.zeros(len(Z) + (len(Z)-1)*(nz))
Y[::nz+1] = Z
print(Z)

[1 2 3 4 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [81]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [82]:
A = np.arange(9).reshape(3,3)
print(A)

A[[0,1]] = A[[1,0]]
print("Swap")
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Swap
[[3 4 5]
 [0 1 2]
 [6 7 8]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [83]:
faces = np.random.randint(0,100,(10,3))
A = np.roll(faces.repeat(2,axis=1),-1,axis=1)
A = A.reshape(len(A)*3,2)
A = np.sort(A,axis=1)
B = A.view( dtype=[('p0',A.dtype),('p1',A.dtype)] )
B = np.unique(B)
print(B)

[( 7, 65) ( 7, 78) ( 9, 20) ( 9, 78) (13, 26) (13, 50) (13, 57) (13, 77)
 (18, 42) (18, 59) (20, 49) (20, 64) (20, 78) (21, 32) (21, 67) (22, 92)
 (22, 97) (26, 57) (30, 41) (30, 63) (32, 67) (41, 63) (42, 59) (49, 64)
 (50, 77) (58, 63) (58, 75) (63, 75) (65, 78) (92, 97)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [84]:
A = np.bincount([1,1,2,3,4,4,6])
B = np.repeat(np.arange(len(A)), A)
print(B)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [85]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [86]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [87]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.83954958,  0.32001035, -0.58882305,  0.96580493, -0.07651145,
       -0.22939168,  0.54698288, -0.5742967 ,  0.41991334,  0.80692625,
        0.86820514,  0.74041619, -0.59911625, -0.20170949, -0.63875596,
        0.97536291,  0.4793628 ,  0.97418144,  0.43296711, -0.54963393,
        0.17001895, -0.30161376, -0.64029033, -0.36514607,  0.64950624,
       -0.85124306,  0.92076589, -0.31117323, -0.66213856,  0.77613981,
       -0.70214517,  0.16362174, -0.74642495, -0.95597881, -0.02586499,
        0.86895187, -0.57912718,  0.06789823,  0.71944272, -0.99934143,
        0.66908592, -0.95580827,  0.33805418,  0.79632981, -0.6141982 ,
       -0.00655782,  0.83861604, -0.30075286,  0.71192954,  0.12058749,
       -0.70876219,  0.71204519,  0.42762258,  0.89776354,  0.83087615,
        0.52666933,  0.03458144,  0.36877516, -0.12793678,  0.03644669,
        0.51624437, -0.0930009 ,  0.38169716,  0.3356746 ,  0.97384049,
        0.18383664,  0.18003073, -0.77187639,  0.53775002,  0.83

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [88]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[12.40664827  5.21588163  7.47434002  7.95578566  8.54908782  8.36035033
  2.72612512 16.90944637  0.81839317  3.27996768]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [89]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[6.36694964e+00 8.48946959e-01 2.17956140e+00 2.31904124e+00
  9.48378765e+00 1.32119556e+01 1.22701439e+01 8.53973554e+00
  1.65471442e+01 1.24721903e-02]
 [8.03554732e-01 7.37359674e+00 1.27813878e+00 2.08454138e+00
  2.23206844e+00 7.74445554e+00 5.47808503e+00 6.18159268e+00
  9.30839602e+00 2.35549995e+00]
 [4.06791822e+00 5.83487697e+00 1.02870151e+01 5.88149525e+00
  8.91554850e+00 6.21830950e+00 1.48841266e+01 8.85347399e-01
  1.63479850e+01 8.88596084e+00]
 [2.48706529e+00 5.80172326e+00 4.83823598e+00 3.40023600e+00
  6.42342244e+00 7.67783254e+00 1.09500889e+01 3.00304660e+00
  1.36731522e+01 3.46556246e+00]
 [1.12723656e+00 9.35435365e+00 3.93569861e+00 6.23885551e+00
  2.92837192e+00 4.44409126e+00 7.96344752e+00 1.02398233e+00
  1.02179132e+01 3.15029334e+00]
 [6.17667420e+00 5.54782259e-01 5.99651638e-01 3.29837847e+00
  9.00767437e+00 1.39130979e+01 1.13161796e+01 9.87697998e+00
  1.60124499e+01 1.60579769e+00]
 [7.56986577e+00 1.71554793e+01 7.00320828e+00 1.47434198e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [90]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[2 1 3 2 4 4 6 5 6 7]
 [4 0 3 3 6 7 5 4 0 7]
 [8 6 3 1 6 3 6 6 2 4]
 [7 2 8 6 3 7 6 6 2 8]
 [4 8 0 3 1 9 2 9 2 4]
 [8 2 8 2 9 5 6 5 7 2]
 [1 7 7 6 9 6 7 9 4 6]
 [2 0 9 0 6 8 2 5 0 1]
 [5 3 2 1 4 2 6 1 4 0]
 [6 7 9 2 0 1 6 3 7 5]]
[[0 0 0 0 0]
 [0 2 1 3 2]
 [0 4 0 3 3]
 [0 8 6 3 1]
 [0 7 2 8 6]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [91]:
Z = np.arange(1,15,dtype=np.uint32)
X = stride_tricks.as_strided(Z,(11,4),(4,4))
print(X)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [92]:
Z = np.random.uniform(0,1,(8,8))

U, S, V = np.linalg.svd(Z) 

rank = np.sum(S > 1e-8)

print(rank)

8


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [93]:
Z = np.random.randint(0,10,50)

print(np.bincount(Z).argmax())

5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [94]:
Z = np.random.randint(0,5,(10,10))

n = 3

a = 1 + (Z.shape[0]-3)

b = 1 + (Z.shape[1]-3)

C = stride_tricks.as_strided(Z, shape=(a, b, n, n), strides=Z.strides + Z.strides)

print(C)

[[[[2 3 3]
   [2 2 0]
   [0 2 2]]

  [[3 3 0]
   [2 0 1]
   [2 2 2]]

  [[3 0 1]
   [0 1 3]
   [2 2 0]]

  [[0 1 2]
   [1 3 4]
   [2 0 3]]

  [[1 2 3]
   [3 4 2]
   [0 3 3]]

  [[2 3 2]
   [4 2 4]
   [3 3 1]]

  [[3 2 0]
   [2 4 3]
   [3 1 4]]

  [[2 0 2]
   [4 3 4]
   [1 4 2]]]


 [[[2 2 0]
   [0 2 2]
   [0 2 3]]

  [[2 0 1]
   [2 2 2]
   [2 3 2]]

  [[0 1 3]
   [2 2 0]
   [3 2 4]]

  [[1 3 4]
   [2 0 3]
   [2 4 3]]

  [[3 4 2]
   [0 3 3]
   [4 3 3]]

  [[4 2 4]
   [3 3 1]
   [3 3 2]]

  [[2 4 3]
   [3 1 4]
   [3 2 2]]

  [[4 3 4]
   [1 4 2]
   [2 2 3]]]


 [[[0 2 2]
   [0 2 3]
   [4 4 4]]

  [[2 2 2]
   [2 3 2]
   [4 4 3]]

  [[2 2 0]
   [3 2 4]
   [4 3 0]]

  [[2 0 3]
   [2 4 3]
   [3 0 2]]

  [[0 3 3]
   [4 3 3]
   [0 2 3]]

  [[3 3 1]
   [3 3 2]
   [2 3 1]]

  [[3 1 4]
   [3 2 2]
   [3 1 1]]

  [[1 4 2]
   [2 2 3]
   [1 1 2]]]


 [[[0 2 3]
   [4 4 4]
   [3 3 2]]

  [[2 3 2]
   [4 4 3]
   [3 2 2]]

  [[3 2 4]
   [4 3 0]
   [2 2 3]]

  [[2 4 3]
   [3 0 2]
   [2 3 4]]

  [[4 3 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [97]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        a,b = index
        super(Symetric, self).__setitem__((a,b), value)
        super(Symetric, self).__setitem__((a,b), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(1,20,(7,7)))
S[2,3] = 42
print(S)

[[14 13 24 20 19 14 19]
 [13 15 15 10 32 15  9]
 [24 15  7 42  5 10 33]
 [20 10  4 11 13 24 17]
 [19 32  5 13 17 17 21]
 [14 15 10 24 17  3 15]
 [19  9 33 17 21 15 15]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [98]:
p, n = 10, 20

M = np.ones((p,n,n))

V = np.ones((p,n,1))

S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])

print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [99]:
X = np.ones((16,16))
Y = 4
Z = np.add.reduceat(np.add.reduceat(X, np.arange(0, X.shape[0], Y), axis=0),
np.arange(0, X.shape[1], Y), axis=1)
print(Z)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [109]:
def iterate(Z):

    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])


    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [110]:
Z = np.arange(10000)

np.random.shuffle(Z)

n = 5


print (Z[np.argsort(Z)[-n:]])


print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9997 9999 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [112]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [114]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [115]:
x = np.random.rand(int(1e8))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 7.52 s per loop
1 loop, best of 5: 410 ms per loop
1 loop, best of 5: 339 ms per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [116]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[5]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [117]:
nums = np.random.randint(0,4,(10,3))
print("Original vector:")
print(nums)
new_nums = np.logical_and.reduce(nums[:,1:] == nums[:,:-1], axis=1)
result = nums[~new_nums]
print("\nRows with unequal values:")
print(result)

Original vector:
[[3 2 0]
 [1 2 2]
 [2 1 0]
 [1 2 1]
 [0 0 2]
 [1 0 0]
 [1 3 0]
 [3 2 0]
 [1 3 1]
 [2 2 2]]

Rows with unequal values:
[[3 2 0]
 [1 2 2]
 [2 1 0]
 [1 2 1]
 [0 0 2]
 [1 0 0]
 [1 3 0]
 [3 2 0]
 [1 3 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [118]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [119]:
arr2D = np.array([[10, 11, 12, 11],
                     [13, 11, 12, 11],
                     [10, 11, 12, 11],
                     [10, 11, 12, 11]])
  
print('Original Array :' ,
      arr2D, sep = '\n')
  
uniqueRows = np.unique(arr2D, 
                       axis = 0)
  
print('Unique Rows:',
      uniqueRows, sep = '\n')

Original Array :
[[10 11 12 11]
 [13 11 12 11]
 [10 11 12 11]
 [10 11 12 11]]
Unique Rows:
[[10 11 12 11]
 [13 11 12 11]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [120]:
A = np.random.uniform(0,10,5)
B = np.random.uniform(0,10,5)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[2.28332489e+00, 3.12313606e+01, 5.75179464e+01, 5.35724113e+00,
        1.85022664e+01],
       [3.44249970e+00, 4.70865755e+01, 8.67180639e+01, 8.07695002e+00,
        2.78953061e+01],
       [2.12271694e+00, 2.90345621e+01, 5.34721624e+01, 4.98041542e+00,
        1.72008261e+01],
       [3.08421335e+00, 4.21859280e+01, 7.76926749e+01, 7.23632221e+00,
        2.49920357e+01],
       [5.50542490e-02, 7.53033051e-01, 1.38684046e+00, 1.29170793e-01,
        4.46116270e-01]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [125]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)   
x_int = np.interp(r_int, r, x)               
y_int = np.interp(r_int, r, y)


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [126]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [127]:
X = np.random.randn(100) 
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.30103447  0.10510157]
